INSERT INTO "items" ("id", "name", "description", "price", "effect_type", "value", "rarity", "image") VALUES ('atk_r1', 'Attaque +', '+10 ATK temporaire', 100, 'BUFF_ATK', 10, 'COMMON', 'attaque.webp'),
('atk_r2', 'Potion Attaque (R2)', '+40% Dégâts', 250, 'BUFF_ATK', 40, 'UNCOMMON', 'attaque.webp'),
('atk_r3', 'Attaque ++', '+20 ATK temporaire', 250, 'BUFF_ATK', 20, 'RARE', 'attaque.webp'),
('atk_r4', 'Potion Attaque (R4)', '+80% Dégâts', 900, 'BUFF_ATK', 80, 'EPIC', 'attaque.webp'),
('atk_r5', 'Potion Attaque (R5)', '+100% Dégâts (x2)', 1500, 'BUFF_ATK', 100, 'LEGENDARY', 'attaque.webp'),
('def_r1', 'Défense +', '+10 DEF temporaire', 100, 'BUFF_DEF', 10, 'COMMON', 'defense.webp'),
('def_r2', 'Potion Défense (R2)', 'Bloque 40% Dégâts', 250, 'BUFF_DEF', 40, 'UNCOMMON', 'defense.webp'),
('def_r3', 'Potion Défense (R3)', 'Bloque 60% Dégâts', 500, 'BUFF_DEF', 60, 'RARE', 'defense.webp'),
('def_r4', 'Potion Défense (R4)', 'Bloque 80% Dégâts', 1000, 'BUFF_DEF', 80, 'EPIC', 'defense.webp'),
('def_r5', 'Potion Défense (R5)', 'Immunité (1 tour)', 1500, 'BUFF_DEF', 100, 'LEGENDARY', 'defense.webp'),
('dmg_r1', 'Coup de Poing (R1)', '20% PV Ennemi', 150, 'DMG_FLAT', 20, 'COMMON', 'coup_poing.webp'),
('dmg_r2', 'Coup de Poing (R2)', '40% PV Ennemi', 350, 'DMG_FLAT', 40, 'UNCOMMON', 'coup_poing.webp'),
('dmg_r3', 'Coup de Poing (R3)', '60% PV Ennemi', 600, 'DMG_FLAT', 60, 'RARE', 'coup_poing.webp'),
('dmg_r4', 'Coup de Poing (R4)', '80% PV Ennemi', 1500, 'DMG_FLAT', 80, 'EPIC', 'coup_poing.webp'),
('dmg_r5', 'K.O Instantané', '100% PV Ennemi', 2500, 'DMG_FLAT', 100, 'LEGENDARY', 'coup_poing.webp'),
('evolution', 'Pierre d''Évolution', 'Fait évoluer un Pokémon', 2000, 'EVOLUTION', 1, 'RARE', 'evolution.webp'),
('evolution_ultime', 'Cristal Ultime', 'Évolution max + Niveau 100', 10000, 'EVOLUTION_MAX', 1, 'LEGENDARY', 'evolution_ultime.webp'),
('heal_r1', 'Potion Basique', '+20 PV', 50, 'HEAL', 20, 'COMMON', 'soin.webp'),
('heal_r2', 'Super Potion', '+50 PV', 150, 'HEAL', 50, 'UNCOMMON', 'soin.webp'),
('heal_r3', 'Hyper Potion', '+100 PV', 300, 'HEAL', 100, 'RARE', 'soin.webp'),
('heal_r4', 'Potion de Soin (R4)', '+80% PV (1 Allié)', 600, 'HEAL', 80, 'EPIC', 'soin.webp'),
('heal_r5', 'Potion Max', '+200 PV', 500, 'HEAL', 200, 'EPIC', 'soin.webp'),
('joker', 'Joker', 'Passe une question', 500, 'JOKER', 1, 'RARE', 'joker.webp'),
('masterball', 'Master Ball', 'Capture garantie', 5000, 'CAPTURE', 100, 'LEGENDARY', 'pokeball.webp'),
('mirror_r5', 'Miroir Magique', 'Double les récompenses', 3000, 'MIRROR', 1, 'EPIC', 'miroir.webp'),
('poison_r4', 'Venin Mortel', '-30% PV/tour', 800, 'STATUS_POISON', 30, 'EPIC', 'poison.webp'),
('pokeball', 'Pokéball', 'Capture un Pokémon', 200, 'CAPTURE', 1, 'COMMON', 'pokeball.webp'),
('sleep_r1', 'Poudre Dodo', 'Sommeil (1 tour)', 200, 'STATUS_SLEEP', 1, 'UNCOMMON', 'dodo.webp'),
('team_r1', 'Soin Ultime (R1)', '+20% PV Équipe', 200, 'HEAL_TEAM', 20, 'UNCOMMON', 'soin_ultime.webp'),
('team_r2', 'Soin Ultime (R2)', '+40% PV Équipe', 400, 'HEAL_TEAM', 40, 'RARE', 'soin_ultime.webp'),
('team_r3', 'Soin Ultime (R3)', '+60% PV Équipe', 800, 'HEAL_TEAM', 60, 'EPIC', 'soin_ultime.webp'),
('team_r4', 'Soin Ultime (R4)', '+80% PV Équipe', 1500, 'HEAL_TEAM', 80, 'LEGENDARY', 'soin_ultime.webp'),
('team_r5', 'Élixir d''Équipe', 'Soigne toute l''équipe', 1500, 'TEAM_HEAL', 100, 'EPIC', 'soin.webp'),
('tokens', 'Sac de Jetons', '10 Jetons Roue', 1000, 'TOKEN_PACK', 10, 'UNCOMMON', 'jetons.webp'),
('traitor_r1', 'Potion Traître', 'Empoisonne l''adversaire (-30 PV)', 300, 'TRAITOR', 30, 'RARE', 'poison.webp'),
('xp_pack', 'Pack XP', '+500 XP Global', 1000, 'XP_BOOST', 500, 'RARE', 'xp.webp');
